# Generated by Django 2.1.7 on 2019-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('units', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
