# Generated by Django 2.1.7 on 2019-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Oliver', max_length=255),
            preserve_default=False,
        ),
    ]
